Certificate
breatheco-de/apiv2 pull request #1050
Opened 2023-08-23 13:44 UTC by tommygonzaleza

2023-08-23 13:46 UTC, tommygonzaleza commented
https://github.com/breatheco-de/breatheco-de/issues/5869

2023-09-06 00:15 UTC, jefer94 requested changes

2023-09-06 00:15 UTC, jefer94 commented on breathecode/certificate/receivers.py
> +    if instance.educational_status == 'GRADUATED':
The certificate just must be autogenerated if the student coming from a saas cohort or academy cohort, if cohort.is_available_as_saas in [False] it does not take in consideration the value in the academy

2023-09-21 19:06 UTC, jefer94 requested changes

2023-09-21 19:06 UTC, jefer94 commented on breathecode/marketing/migrations/0074_alter_formentry_attribution_id.py
> +# Generated by Django 3.2.18 on 2023-08-31 19:57
The migrations didn't run

2023-09-21 19:06 UTC, jefer94 commented on breathecode/certificate/actions.py
> +        if (not cohort.never_ends) and cohort.stage != 'ENDED':
Changes in the logic of certificate require tests

2023-10-20 23:32 UTC, merged