Event checkin
breatheco-de/apiv2 pull request #1309
Opened 2024-03-18 23:22 UTC by gustavomm19

https://github.com/breatheco-de/breatheco-de/issues/6869

2024-03-19 01:50 UTC, jefer94 requested changes

2024-03-19 01:50 UTC, jefer94 commented on breathecode/commons/admin.py
> +TMA.actions = TMA.actions + [upload]
Remove it

2024-03-19 01:50 UTC, jefer94 commented on breathecode/services/google_cloud/big_query.py
> +        diff = cls._map_schema(diff)
Avoid the variable shadowing

2024-03-26 00:05 UTC, jefer94 approved these changes

2024-03-26 00:07 UTC, jefer94 commented
This PR must be tested on dev, if this implementation fails could be necessary migrate to a document database using partitions

2024-03-26 21:16 UTC, tommygonzaleza approved these changes

2024-03-26 21:16 UTC, merged