dd platform question to nps
breatheco-de/apiv2 pull request #1428
Opened 2024-07-24 19:06 UTC by gustavomm19

https://github.com/breatheco-de/breatheco-de/issues/7574

2024-07-24 21:43 UTC, tommygonzaleza submitted a review, later dismissed

2024-07-24 23:22 UTC, jefer94 requested changes

2024-07-24 23:22 UTC, jefer94 commented on breathecode/feedback/tests/tasks/tests_generate_user_cohort_survey_answers.py
> +                    print(dict)
👀

2024-07-24 23:22 UTC, jefer94 commented on breathecode/feedback/tests/tasks/tests_generate_user_cohort_survey_answers.py
> +                            "id": (n * 5) + 4,
why this is happening?

2024-07-24 23:22 UTC, jefer94 commented on breathecode/feedback/models.py
> +    platform_and_content = models.BooleanField(default=False)
This solution is a bit inaccurate https://github.com/breatheco-de/breatheco-de/issues/7574#issuecomment-2249049862

2024-07-24 23:25 UTC, jefer94 requested changes

2024-07-24 23:25 UTC, jefer94 commented on breathecode/feedback/tests/tasks/tests_generate_user_cohort_survey_answers.py
> +                    answer(
There isn't any test for the case of a sass academy and cohort. two cases

2024-07-25 22:55 UTC, jefer94 requested changes

2024-07-25 22:55 UTC, jefer94 commented on breathecode/feedback/models.py
> +    aditional_question = models.CharField(
There is a typo https://www.oxfordlearnersdictionaries.com/us/definition/english/additional?q=additional

2024-07-25 22:55 UTC, jefer94 commented on breathecode/feedback/models.py
> +    aditional_question = models.CharField(
`additional_question` isn't descriptive enough

2024-07-29 08:23 UTC, jefer94 requested changes

2024-07-29 08:23 UTC, jefer94 commented on breathecode/feedback/tests/tasks/tests_generate_user_cohort_survey_answers.py
> +                    "question_by_slug": "PLATFORM",
If a cohort is set and is available as saas or an academy is not available as saas, only an answer should be generated related to `"question_by_slug": "PLATFORM",`

2024-07-29 08:23 UTC, jefer94 commented on breathecode/feedback/tests/tasks/tests_generate_user_cohort_survey_answers.py
> +                    "question_by_slug": "PLATFORM",
So, I mean a case must be 

```py
answers = [
                {
                    "title": f"How has been your experience with the platform and content?",
                    "lowest": "not good",
                    "highest": "very good",
                    "cohort_id": None,
                    "academy_id": None,
                    "question_by_slug": "PLATFORM",
                 },
]
```

2024-07-30 19:14 UTC, jefer94 requested changes

2024-07-30 19:14 UTC, jefer94 commented on breathecode/feedback/tasks.py
> +        if not survey.cohort.available_as_saas:
`cohort.available_as_saas` could be None in this case it uses `cohort.academy.available_as_saas`

2024-07-30 19:19 UTC, jefer94 commented on breathecode/feedback/tasks.py
> +        if not survey.cohort.available_as_saas:
```py
        if survey.cohort.available_as_saas is False or (survey.cohort.available_as_saas is None and survey.cohort.academy.available_as_saas):
```

2024-07-30 20:12 UTC, jefer94 approved these changes

2024-08-05 20:35 UTC, merged