Datastore/pagination
breatheco-de/apiv2 pull request #144
Opened 2021-08-13 21:06 UTC by alexscoelho

Datastore pagination and github username

2021-08-16 12:39 UTC, jefer94 requested changes

2021-08-16 12:39 UTC, jefer94 commented on breathecode/activity/views.py
> +        limit = request.GET.get('limit')
Add this pagination to `ActivityMeView` too

2021-08-16 12:39 UTC, jefer94 commented on breathecode/activity/tests/urls/tests_cohort.py
> +    def test_get_activities(self):
We need a test:

1. With more that 100 activities without passing paginations that just get 100 elements
2. With 20 elements, the `limit` could be 10, the `offset` could be 0, this returns the first 10 elements
3. With 20 elements, the `limit` could be 10, the `offset` could be 10, this returns the last 10 elements
4. With 20 elements, the `limit` could be 10, the `offset` could be 20, this returns zero elements

This test should copy and paste to `activity/me` and remember you should use a generator to generate a list with 10 or 100 elements of same dictionary

2021-08-25 09:23 UTC, jefer94 requested changes

2021-08-25 09:23 UTC, jefer94 commented on breathecode/activity/actions.py
> +def paginated_datastore(public_iter):
this is being used?

2021-08-25 09:23 UTC, jefer94 commented on breathecode/activity/tests/urls/tests_cohort.py
> +    @patch.object(Datastore, 'count', new=datastore_count_mock(7957599))
You should prevent call `.count` and using this mock if `limit` or `offset` is not set

2021-08-25 09:23 UTC, jefer94 commented on breathecode/activity/tests/urls/tests_cohort.py
> +        self.assertEqual(len(json), 100)
This assert need be more exact

2021-08-25 09:23 UTC, jefer94 commented on breathecode/activity/tests/urls/tests_cohort.py
> +        self.assertEqual(mock.fetch.call_args_list, [
Missing the asserts to `count` function

2021-08-25 09:23 UTC, jefer94 commented on breathecode/activity/tests/urls/tests_cohort.py
> +        results = len(json['results'])
This test need perform a test about the wrapper of pagination

2021-08-25 15:59 UTC, alexscoelho reviewed
Fixed comments!

2021-08-30 22:28 UTC, jefer94 approved these changes

2021-08-30 22:57 UTC, merged