Add micro cohorts to cohort model
breatheco-de/apiv2 pull request #1494
Opened 2024-11-07 23:40 UTC by gustavomm19

https://github.com/breatheco-de/breatheco-de/issues/7592

2024-11-12 13:25 UTC, tommygonzaleza commented
Add color to the cohort

2024-11-18 18:52 UTC, tommygonzaleza requested changes

2024-11-19 15:30 UTC, jefer94 commented on breathecode/admissions/receivers.py
> +def post_save_cohort_user(sender: Type[CohortUser], instance: CohortUser, **kwargs: Any):
If you join this code with the other graduation logic you could reduce your test size

2024-11-26 15:42 UTC, jefer94 approved these changes

2024-11-26 15:46 UTC, jefer94 requested changes

2024-11-26 15:46 UTC, jefer94 commented on breathecode/admissions/receivers.py
> +def join_to_micro_cohorts(cohort_user):
Add two tests

2024-12-03 14:22 UTC, merged