❇️ added tech/slug
breatheco-de/apiv2 pull request #1495
Opened 2024-11-08 21:11 UTC by lumi-tip

### Issue: https://github.com/breatheco-de/breatheco-de/issues/7920

2024-11-11 13:06 UTC, tommygonzaleza requested changes

2024-11-11 13:06 UTC, tommygonzaleza commented on breathecode/registry/urls/v1.py
> +    path("technology", PublicTechnologyView.as_view(), name="technology"),
TechnologyView without Public

2024-11-11 13:06 UTC, tommygonzaleza commented on breathecode/registry/views.py
> +class PublicTechnologyView(APIView):
Name it TechnologyView

2024-11-14 23:25 UTC, jefer94 requested changes

2024-11-14 23:25 UTC, jefer94 commented on breathecode/registry/views.py
> +        items = items.order_by("sort_priority")
Set the default sort in the APIViewExtensions (it has some advantages), also enable the paginate extension (each View requires to be paginated)

Example:
```py
    extensions = APIViewExtensions(cache=CohortCache, paginate=True, sort="-kickoff_date")
```

2024-11-15 20:24 UTC, merged