Input search bar
breatheco-de/apiv2 pull request #1520
Opened 2024-12-19 20:38 UTC by avanegasp

Add all tests_academy_keyword_cluster file with lang, like and visibility values tests from cero.

2024-12-19 20:53 UTC, avanegasp commented
https://github.com/breatheco-de/breatheco-de/issues/7598

2025-01-14 15:51 UTC, tommygonzaleza requested changes

2025-01-14 15:51 UTC, tommygonzaleza commented on breathecode/registry/views.py
> +            if "," not in lang:
Remove this unnecessary condition

2025-02-04 13:47 UTC, tommygonzaleza requested changes

2025-02-04 13:47 UTC, tommygonzaleza commented on breathecode/registry/views.py
> +        lang = request.GET.get("lang", None)
It should look like this one: https://github.com/breatheco-de/apiv2/blob/21d6cfe26a242526360c91ae1b827346348e7c50/breathecode/registry/views.py#L212

2025-02-13 22:06 UTC, avanegasp commented
https://github.com/orgs/breatheco-de/projects/7/views/1?filterQuery=avanegas&pane=issue&itemId=71127245&issue=breatheco-de%7Cbreatheco-de%7C7598

2025-02-14 18:58 UTC, avanegasp commented
https://github.com/breatheco-de/admin/pull/403

2025-02-18 13:09 UTC, tommygonzaleza requested changes

2025-02-18 13:09 UTC, tommygonzaleza commented on breathecode/registry/views.py
> +                items = items.filter(Q(lang__iexact=param) | Q(lang="") | Q(lang__isnull=True))
You should only get those filtered by the language given, the code will look like this: `lookup["lang"] = lang`

2025-02-18 14:26 UTC, tommygonzaleza requested changes

2025-02-18 14:26 UTC, tommygonzaleza commented on breathecode/registry/views.py
> +                items = items.filter(Q(lang__iexact=param) | Q(lang="") | Q(lang__isnull=True))
Add a validation to avoid filtering by lang when lang is an empty string

2025-03-01 15:49 UTC, avanegasp commented on breathecode/registry/views.py
> +                items = items.filter(Q(lang__iexact=param) | Q(lang="") | Q(lang__isnull=True))
1. If lang is in request.GET and has a value, it is added to lookup, then items is filtered with lookup.

2. Filtering by lang when it is an empty string: The condition if lang: ensures that it is only added to lookup if it has a value.

2025-03-04 13:36 UTC, tommygonzaleza approved these changes

2025-03-04 13:39 UTC, merged