add websockets
breatheco-de/apiv2 pull request #348
Opened 2022-03-01 21:54 UTC by jefer94

2022-03-16 00:05 UTC, alesanchezr requested changes
Important changes below

2022-03-16 00:05 UTC, alesanchezr commented on breathecode/websocket/consumers.py
> +class OnlineFromCohortConsumer(AsyncJsonWebsocketConsumer):
lets leave the online status for the other consume below, this one only will take care of the classroom activity:
- Student Reactions?
- Rising the hand?
- Classroom chat?

Note: do not implement any of this yet, it has to be discused.

2022-03-16 00:05 UTC, alesanchezr commented on breathecode/websocket/consumers.py
> +class OnlineFromAcademyConsumer(AsyncJsonWebsocketConsumer):
This consumer will take care of the onlin status for now.

2022-03-16 00:05 UTC, alesanchezr commented on breathecode/asgi.py
> +from channels.auth import AuthMiddlewareStack
Remember to update the Procfile to stop using unicorn.

2022-08-01 06:33 UTC, closed without merging

2022-08-01 06:38 UTC, jefer94 commented
This PR was closed because it went crazy