add /cohort/me in admissions
breatheco-de/apiv2 pull request #380
Opened 2022-04-08 09:35 UTC by jefer94

2022-04-08 19:59 UTC, jefer94 commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2212

2022-04-12 23:10 UTC, alesanchezr requested changes

2022-04-12 23:10 UTC, alesanchezr commented on breathecode/admissions/urls.py
> +    path('cohort/me', CohortMeView.as_view(), name='cohort_me'),
/academy/cohort/me

2022-04-20 18:37 UTC, alesanchezr approved these changes

2022-04-20 18:37 UTC, merged