add remote available to serializers
breatheco-de/apiv2 pull request #404
Opened 2022-05-07 01:41 UTC by gustavomm19

2022-05-09 16:16 UTC, jefer94 requested changes

2022-05-09 16:16 UTC, jefer94 commented on breathecode/events/views.py
> +            if (len(lookups['id__in']) != len(items)):
Should be util show the slug of events cannot be deleted

2022-05-09 17:50 UTC, jefer94 requested changes

2022-05-09 17:50 UTC, jefer94 commented on breathecode/events/views.py
> +                return Response('The following events are not draft: ' + not_draft, status=status.HTTP_200_OK)
Use a `ValidationException` with status code 400

2022-05-10 21:35 UTC, alesanchezr approved these changes

2022-05-10 21:35 UTC, merged