Filter assets by keywords done
breatheco-de/apiv2 pull request #618
Opened 2022-11-02 22:41 UTC by tommygonzaleza

2022-11-02 22:41 UTC, tommygonzaleza commented
Issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3389

2022-11-07 19:39 UTC, jefer94 requested changes

2022-11-07 19:39 UTC, jefer94 commented on breathecode/registry/views.py
> +            lookup['sync_status__iexact'] = param
`lookup['sync_status'] = param.upper()` in the two sides

2022-11-07 19:39 UTC, jefer94 commented on breathecode/registry/views.py
> +            lookup['test_status__iexact'] = param
`lookup['test_status'] = param.upper()` in the two sides

2022-11-07 19:39 UTC, jefer94 commented on breathecode/registry/views.py
> +            items = items.filter(seo_keywords__slug__in=[p.lower() for p in param.split(',')])
Remove the `.lower()` because the django field does not validate the uppercase and is possible has a slug with uppercase

2022-11-09 02:22 UTC, merged