mandatory category test finished
breatheco-de/apiv2 pull request #644
Opened 2022-11-17 16:47 UTC by Andresgarciasch

2022-11-17 16:47 UTC, Andresgarciasch commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3622

2022-11-21 19:21 UTC, jefer94 commented
Pull the changes from development branch and fix the tests that appear with `pipenv run ptest`

2022-11-21 19:23 UTC, jefer94 requested changes

2022-11-21 19:23 UTC, jefer94 commented on breathecode/registry/serializers.py
> +            print(dir(e))
remove prints

2022-11-21 19:23 UTC, jefer94 commented on breathecode/registry/tests/urls/tests_academy_asset.py
> +#class RegistryTestAsset2(TestCase)
Remove the comment

2022-11-21 19:23 UTC, jefer94 commented on breathecode/registry/tests/urls/tests_academy_asset.py
> +        self.assertEqual(self.bc.database.list_of('registry.Asset'), [])
Write tests until a new asset was created

2022-12-13 20:27 UTC, closed without merging