Filters on article comment pipeline
breatheco-de/apiv2 pull request #648
Opened 2022-11-22 02:19 UTC by gustavomm19

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3413

2022-11-22 11:41 UTC, tommygonzaleza approved these changes

2022-11-22 22:07 UTC, jefer94 requested changes

2022-11-22 22:07 UTC, jefer94 commented on breathecode/registry/views.py
> +            if param == 'true':
Should be fine also support filter by `delivered='false'`

2022-11-29 21:45 UTC, tommygonzaleza approved these changes

2022-11-29 21:45 UTC, merged