Bulk delete for certificate (missing) and pagination for cohort students
breatheco-de/apiv2 pull request #66
Opened 2021-05-20 15:38 UTC by alexscoelho

Bulk delete for certificate (missing) and pagination for cohort students

2021-05-26 00:07 UTC, alesanchezr commented on breathecode/certificate/views.py
> +        if cohort_id is None or user_id is None:
Borra toda la funcionalidad de cohort_id y user_id porque no es parte de bulk.

2021-06-01 22:04 UTC, jefer94 requested changes

2021-06-01 22:04 UTC, jefer94 commented on breathecode/certificate/views.py
> +            raise APIException(
Change it for ValidationException and pass a keywork param called slug

2021-06-04 00:18 UTC, jefer94 commented
@alexscoelho currently this branch need a pull from development

2021-06-10 13:52 UTC, closed without merging

2021-06-10 13:52 UTC, alexscoelho commented
features already in last PR