add plan duration
breatheco-de/apiv2 pull request #709
Opened 2023-01-15 03:03 UTC by jefer94

2023-02-09 10:52 UTC, tommygonzaleza commented on breathecode/payments/urls.py
> +    path('me/planfinancing/<int:plan_financing_id>', MeSubscriptionView.as_view()),
Why is this url repeated but with different views, how will it determine which view it should take

2023-02-09 10:58 UTC, tommygonzaleza commented on breathecode/payments/views.py
> +        items = Subscription.objects.filter(Q(valid_until__gte=now) | Q(valid_until=None), user=request.user)
Shouldn't it be looking for `PlanFinancing` instead of `Subscription`?

2023-02-09 19:49 UTC, alesanchezr submitted a review, later dismissed

2023-02-09 19:49 UTC, tommygonzaleza requested changes

2023-02-09 19:49 UTC, tommygonzaleza commented on breathecode/payments/views.py
> +        items = Subscription.objects.filter(Q(valid_until__gte=now) | Q(valid_until=None), user=request.user)
Shouldn't it be looking for `PlanFinancing` instead of `Subscription`?

2023-02-14 23:41 UTC, alesanchezr approved these changes

2023-02-14 23:41 UTC, merged