make kickoff_date not nullable again
breatheco-de/apiv2 pull request #727
Opened 2023-01-26 19:09 UTC by gustavomm19

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3988

2023-01-30 14:35 UTC, tommygonzaleza requested changes

2023-01-30 14:35 UTC, tommygonzaleza commented on breathecode/admissions/serializers.py
> -        if 'never_ends' in data and data['never_ends'] and kickoff_date:
Debes agregar esta validacion pero para 'ending_date'

2023-01-30 23:50 UTC, jefer94 commented
Add test case where you is trying to set `kickoff_date` as `null` and see the result

2023-02-03 19:10 UTC, jefer94 approved these changes

2023-02-03 19:11 UTC, merged