Event type filter
breatheco-de/apiv2 pull request #728
Opened 2023-01-31 00:18 UTC by gustavomm19

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4234

2023-01-31 18:15 UTC, tommygonzaleza requested changes

2023-01-31 18:15 UTC, tommygonzaleza commented on breathecode/events/urls.py
> +    path('academy/eventype/<slug:even_type_slug>',
cambia `<slug:even_type_slug>` por `<slug:event_type_slug>`

2023-01-31 18:56 UTC, tommygonzaleza submitted a review, later dismissed

2023-02-01 21:29 UTC, jefer94 approved these changes

2023-02-01 21:29 UTC, merged