Montoring script
breatheco-de/apiv2 pull request #751
Opened 2023-02-10 02:30 UTC by tommygonzaleza

Review is required as I wasn't able to test it

2023-02-10 02:30 UTC, tommygonzaleza commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4355

2023-02-10 17:37 UTC, tommygonzaleza commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4365

2023-02-10 19:21 UTC, jefer94 requested changes

2023-02-10 19:21 UTC, jefer94 commented on breathecode/monitoring/scripts/online_event_published_without_live_stream_url.py
> +                                                         live_stream_url='',
```py
live_stream_url == '' or live_stream_url == None
```

2023-02-10 19:21 UTC, jefer94 commented on breathecode/monitoring/scripts/online_event_published_without_live_stream_url.py
> +        event.status = 'draft'
```py
        event.status = 'DRAFT'
```

2023-02-10 19:21 UTC, jefer94 commented on breathecode/monitoring/scripts/online_event_published_without_live_stream_url.py
> +        serializer = EventSerializer(data=event, context={'academy_id': None})
Is not necessary use the serializer, you can use `event.save()` or `published_without_live_stream_url.update(status='DRAFT')`

2023-02-21 19:19 UTC, jefer94 requested changes

2023-02-21 19:19 UTC, jefer94 commented on breathecode/monitoring/scripts/online_event_published_without_live_stream_url.py
> +        if event.is_valid():
`is_valid()` is a method of DRF's Serializers

2023-02-21 19:19 UTC, jefer94 commented on breathecode/monitoring/scripts/online_event_published_without_live_stream_url.py
> +        if event.is_valid():
You must not use this method because `Event` doesn't have it

2024-04-18 19:54 UTC, closed without merging