Final Project Mode Corrections/Changes
breatheco-de/apiv2 pull request #768
Opened 2023-02-23 00:20 UTC by gustavomm19

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4251

2023-02-27 20:26 UTC, tommygonzaleza submitted a review, later dismissed

2023-03-03 20:14 UTC, jefer94 requested changes

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +                    f'You can upload only files on the following formats: {",".join(MIME_ALLOW)}')
Only allow mime types of images

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +                'slug': slug,
Remove this

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +                'categories': [],
Remove this

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +                'name': name,
Remove this

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +            data['thumbnail'] = data['url'] + '-thumbnail'
If you don't use the thumbnail, remove this

2023-03-03 20:14 UTC, jefer94 commented on breathecode/assignments/views.py
> +        members_set = set(payload[0]['members'])
`user_id` will be `request.user.id` in all cases

2023-03-07 20:08 UTC, jefer94 commented
Check the corrections about the object that return the upload view

2023-03-07 20:41 UTC, merged