add post and delete to visibility settings
breatheco-de/apiv2 pull request #770
Opened 2023-02-24 21:53 UTC by gustavomm19

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4421

2023-02-27 20:48 UTC, tommygonzaleza approved these changes

2023-02-27 22:12 UTC, jefer94 requested changes

2023-02-27 22:12 UTC, jefer94 commented on breathecode/events/views.py
> +        other_event_type = EventType.objects.filter(visibility_settings__id=visibility_setting_id).exclude(
Delete this visibility just in this `EventType`, a academy is not able to edit the visibility setting of another academy, if no one `EventType` of any academy is using this visibilitysetting, this must be removed

2023-02-27 22:12 UTC, jefer94 commented on breathecode/events/views.py
> +        visibility_setting, created = EventTypeVisibilitySetting.objects.get_or_create(syllabus=syllabus,
Then, you got the instance of visibility setting, so you need add this to the many to many to `EventType` if it ain't already in it

2023-03-03 19:37 UTC, jefer94 requested changes

2023-03-03 19:37 UTC, jefer94 commented on breathecode/events/views.py
> +        if 'syllabus' in request.data:
This is a example of how to do this https://github.com/breatheco-de/apiv2/blob/f8023078ea23dd457a6fcf954d64348fca530488/breathecode/admissions/views.py#L1372

2023-03-03 19:37 UTC, jefer94 commented on breathecode/events/views.py
> +        visibility_setting, created = EventTypeVisibilitySetting.objects.get_or_create(syllabus=syllabus,
```py
if visibility_setting not in event_type.visibility_settings:
    event_type.visibility_settings.add(visibility_setting)
```

2023-03-03 19:37 UTC, jefer94 commented on breathecode/events/views.py
> +                                                    academy=academy_id).exclude(slug=event_type_slug).first()
`.exists()`

2023-03-03 19:52 UTC, jefer94 requested changes

2023-03-03 19:52 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting.py
> +        self.assertEqual(response.status_code, 400)
Add a case when you is trying of get a visibility settings and it is found

2023-03-03 19:52 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting_id.py
> +        self.assertEqual(response.status_code, 204)
Add database test with
`self.bc.database.list_of('events.EventTypeVisibilitySetting')`

2023-03-03 19:52 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting_id.py
> +        self.assertEqual(response.status_code, 204)
Add a test to check the ids
```py
self.bc.check.queryset_with_pks(model.event_type.visibility_settings.all(), [2])
```

Where 2 is the primary key of resource added to many to many and `model.event_type.visibility_settings.all()` is the many to many to be checked

2023-03-04 05:31 UTC, jefer94 requested changes

2023-03-04 05:31 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting_id.py
> +        self.assertEqual(response.status_code, 400)
Add the test of database to the rest of tests

2023-03-04 05:31 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting.py
> +        self.assertEqual(response.status_code, 400)
Add test of database to the rest of tests

2023-03-07 20:16 UTC, jefer94 requested changes

2023-03-07 20:16 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting.py
> +        self.bc.check.queryset_with_pks(model.event_type.visibility_settings.all(), [1])
Check also the properties is being put in `EventTypeVisibilitySetting`

2023-03-07 20:16 UTC, jefer94 commented on breathecode/events/tests/urls/tests_academy_eventype_slug_visibilitysetting.py
> +        self.assertEqual(response.status_code, 400)
So think you is modifying 2 tables, `EventTypeVisibilitySetting` and the handler between it and `EventType`

2023-03-07 21:47 UTC, jefer94 approved these changes

2023-03-07 21:58 UTC, merged