add feature flags
breatheco-de/apiv2 pull request #820
Opened 2023-03-18 07:56 UTC by jefer94

2023-03-21 22:07 UTC, tommygonzaleza commented
- [ ] Optimizar entrega de los contextos

2023-03-21 23:17 UTC, tommygonzaleza requested changes
Modificar el key y el kind de todos los contexts

2023-03-21 23:17 UTC, tommygonzaleza commented on breathecode/authenticate/permissions/contexts.py
> +    key = f'user-{user.id}'
El key no debe llevar `user-`

2023-03-21 23:17 UTC, tommygonzaleza commented on breathecode/authenticate/permissions/contexts.py
> +    kind = 'user-data'
El kind no debe llevar `-data`

2023-03-28 21:22 UTC, tommygonzaleza requested changes

2023-03-28 21:22 UTC, tommygonzaleza commented on breathecode/events/actions.py
> +        a_least_one_resource_linked = (Q(selected_cohort__isnull=False)
`at_least...` en vez `a_least...`

2023-03-29 17:37 UTC, tommygonzaleza requested changes

2023-03-29 17:37 UTC, tommygonzaleza commented on breathecode/payments/models.py
> +                'time_of_life_unit')
Aqui no hay un error de sintaxis?

2023-03-29 17:37 UTC, tommygonzaleza commented on breathecode/payments/models.py
> +                'and time_of_life_unit')
Y aqui

2023-03-29 17:37 UTC, tommygonzaleza commented on breathecode/payments/models.py
> +                'If the plan is renewable and a not have free trial available, you must set time_of_life '
Y aqui

2023-03-29 17:37 UTC, tommygonzaleza commented on breathecode/payments/models.py
> +                'time_of_life_unit')
Mira como hay dos strings pero no estan concatenados ni nada

2023-03-29 18:19 UTC, alesanchezr approved these changes

2023-03-29 18:26 UTC, alesanchezr approved these changes

2023-03-30 03:52 UTC, merged

2023-03-30 07:54 UTC, jefer94 commented on breathecode/payments/models.py
> +                'time_of_life_unit')
En python 

```py
a = ('123'
     '456')
```

=

```py
a = '123456'
```

2023-03-30 07:55 UTC, jefer94 commented on breathecode/payments/models.py
> +                'time_of_life_unit')
es basicamente una concatenacion, python no necesita de los + para esto