GET feedback/review returning public reviews without authorization
breatheco-de/apiv2 pull request #832
Opened 2023-03-28 19:34 UTC by tommygonzaleza

2023-03-28 19:57 UTC, jefer94 requested changes

2023-03-28 19:57 UTC, jefer94 commented on breathecode/feedback/views.py
> +    items = Review.objects.filter(is_public=True)
filter by status done

2023-03-28 19:57 UTC, jefer94 commented on breathecode/feedback/views.py
> +    items = Review.objects.filter(is_public=True)
`total_rating is None or total_rating >= 0 and <= 10`

2023-03-28 19:57 UTC, jefer94 commented on breathecode/feedback/views.py
> +    items = Review.objects.filter(is_public=True)
`total_rating__isnull=False or comments__isnull=False`

2023-03-28 19:57 UTC, jefer94 commented on breathecode/feedback/views.py
> +    lookup = {}
https://breathecode-test.herokuapp.com/admin/feedback/review/784/change/?_changelist_filters=status__exact%3DDONE this commentary is positive, but the grade ain't positive, it not have sense, investigate why

2023-03-28 19:57 UTC, jefer94 commented on breathecode/feedback/views.py
> +    items = items.filter(**lookup).order_by('-created_at')
Investigate the range of `total_rating` if each platform use a custom range, the information must be sanity before can be used

2023-03-29 18:54 UTC, alesanchezr approved these changes

2023-03-29 18:54 UTC, merged