Test: When adding a new member to academy, if it exists already as member with role=student it should update it instead of creating it. #1504
breatheco-de/apiv2 pull request #91
Opened 2021-06-11 00:33 UTC by 99lalo

2021-06-11 16:01 UTC, jefer94 requested changes

2021-06-11 16:01 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +    def test_academy_id_member_post_user_with_student_role(self):
We need a new test like it, the current profile as student and the new as teacher

2021-06-14 15:30 UTC, jefer94 requested changes

2021-06-14 15:30 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        response = self.client.post(url, data)
Test the data in `response.json()`

2021-06-14 15:30 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        expected = {'detail': "User does not exists, do you want to invite it?",
Use the `slug` of `ValidationException`

2021-06-14 15:53 UTC, jefer94 requested changes

2021-06-14 15:53 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        model2 = self.generate_models(role='teacher', capability='crud_member')
I think this line should be removed

2021-06-14 15:53 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        expected = {'detail': "Please specify user id or member email",
Add slug

2021-06-14 15:53 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        expected = {'detail': f'This user is already a member of this academy as {role} ({role})',
Add slug

2021-06-14 15:53 UTC, jefer94 commented on breathecode/authenticate/tests/urls/tests_academy_id_member.py
> +        model2 = self.generate_models(role='teacher', capability='crud_member')
The model2

2021-06-14 19:08 UTC, jefer94 approved these changes

2021-06-14 19:09 UTC, jefer94 commented
@alesanchezr is done

2021-06-14 19:30 UTC, jefer94 commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1504

2021-06-15 21:07 UTC, alesanchezr approved these changes

2021-06-15 21:07 UTC, merged