EventCheckin post created
breatheco-de/apiv2 pull request #930
Opened 2023-06-05 22:52 UTC by tommygonzaleza

2023-06-05 22:53 UTC, tommygonzaleza commented
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5344

2023-06-06 20:06 UTC, jefer94 requested changes

2023-06-06 20:06 UTC, jefer94 commented on breathecode/events/serializers.py
> +        exclude = ()
Can a check-in be created with status DONE? I think it shouldn't be possible

2023-06-06 20:17 UTC, jefer94 requested changes

2023-06-06 20:17 UTC, jefer94 commented on breathecode/events/views.py
> +
```py
lang = get_user_language(request)
```

2023-06-06 23:24 UTC, merged