Academy service crud added
breatheco-de/apiv2 pull request #936
Opened 2023-06-08 20:50 UTC by tommygonzaleza

2023-06-08 23:34 UTC, jefer94 requested changes

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +        if 'price_per_unit' not in request.data:
This must be in serializer validation method

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +        if mentorship_service_set_id := request.GET.get('mentorship_service_set_id'):
Change to `mentorship_service_set`

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +        if event_type_set_id := request.GET.get('event_type_set_id'):
Change to `event_type_set`

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +            raise ValidationException(translation(lang,
This must be in serializer validation method

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +            raise ValidationException(translation(lang,
This must be in serializer validation method

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                                  slug='not-found'),
wrong slug

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                                  slug='not-found'),
wrong slug

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                      code=404)
bad status code

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                      code=404)
bad status code

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                                  slug='missing-price_per_unit'),
wrong slug

2023-06-08 23:34 UTC, jefer94 commented on breathecode/payments/views.py
> +                                      code=404)
bad status code

2023-06-12 19:36 UTC, tommygonzaleza commented
En el metodo PUT no movi las validaciones para obtener el academyservice porque lo necesito para pasarselo al serializador

2023-06-13 20:30 UTC, merged